# Generated by Django 4.2.7 on 2024-06-07 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('token_auth', '0003_alter_useraddress_apartment_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraddress',
            name='city',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='country',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='user',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='UserAddress',
        ),
    ]
