# Generated by Django 5.0.6 on 2024-06-12 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='status',
            field=models.CharField(choices=[('SHIPPED', 'Shipped'), ('PROCESSING', 'Processing'), ('DELIVERED', 'Delivered'), ('CANCELED', 'Canceled')], default='SHIPPED', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
