# Generated by Django 5.0.6 on 2024-06-18 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_alter_city_country'),
        ('product', '0006_rename_order_orderproduct_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='customer_address',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='address.useraddress'),
            preserve_default=False,
        ),
    ]
